---
on:
  workflow_call:

jobs:
  compose-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: apt-get update && apt-get install -y yamllint
      - name: Setup NodeJS
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: '24.x'
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Lint all YAML files
        run: |
          yamllint -f github -d "{extends: default, rules: {line-length: {max: 160, level: warning}}}" -- $(git ls-files '*compose.yaml' '*compose.yml')
      - name: Lint compose files
        uses: docker-compose-linter/dclint-github-action@18659f6a7956706cb67cf9c1ad5e55f4352cbc17 # v1.6.0
        with:
          max-warnings: 0
